
version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.16.1
    deploy:
      resources:
        limits:
          cpus: '0.8'
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
      - ./nodeserver/projects/:/etc/projects
    ports:
      # - "80:80"
      - "80:80"
      - "443:443"
    links:
      - nodeserver
    expose:
      - "80"
  nodeserver:
    container_name: nodeserver
    privileged: true
    build: "./nodeserver"
    deploy:
      resources:
        limits:
          cpus: '1'
    volumes:
      - ./nodeserver/ecosystem.config.js:/data/ecosystem.config.js
      - ./nodeserver/projects:/data/projects
      - ./nodeserver/projects/nest_project:/data/projects/nest_project
      - ./nodeserver/start.sh:/data/start.sh
      - ./nodeserver/fonts/Chinese:/usr/share/fonts/Chinese
    # nodeserver 容器启动脚本
    entrypoint: sh "/data/start.sh"
    tty: true
    links:
      - db
      - redis
      # - javaserver
    ports:
      - "3000:3000"
      - "3322:22"
    expose:
      - "3000"
  # javaserver:
  #   container_name: javaserver
  #   privileged: true
  #   build: "./javaserver"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'
  #   volumes:
  #     - ./javaserver/projects:/data/projects
  #     - ./javaserver/start.sh:/data/start.sh
  #   # javaserver 容器启动脚本
  #   entrypoint: sh "/data/start.sh"
  #   tty: true
  #   links:
  #     - db
  #     - redis
  #   expose:
  #     - "8080"
  db:
    container_name: db
    deploy:
        resources:
            limits:
                cpus: "1"
    image: mysql:8.0
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4', #设置数据库表的数据集
      '--collation-server=utf8mb4_unicode_ci', #设置数据库表的数据集
    ]
    restart: always
    volumes:
        - ./mysql/conf/conf.d:/etc/mysql/conf.d
        - ./mysql/logs:/var/log/mysql
        - ./mysql/data:/var/lib/mysql
        - ./mysql/export:/home/export
        - ./mysql/import:/home/import
    environment:
        TZ: Asia/Shanghai
        MYSQL_ROOT_PASSWORD: 123456Aa
        MYSQL_DATABASE: test
        MYSQL_USER: admin
        MYSQL_PASSWORD: 123456Aa
    ports:
        - "3306:3306"
    expose:
        - "3306"
  redis:
    container_name: redis
    image: redis:5.0
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: '1'
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - "6379"
    tty: true
    ports:
      - "6379:6379"


